Champions_dict_tft13 = {
    "TFT13_Akali" : "Akali",
    "TFT13_Ambessa" : "Ambessa",
    "TFT13_Amumu" : "Amumu",
    "TFT13_Beardy" : "Lloris",
    "TFT13_Blitzcrank" : "Blitzcrank",
    "TFT13_Blue" : "Powder",
    "TFT13_Caitlyn" : "Caitlyn",
    "TFT13_Camille" : "Camille",
    "TFT13_Cassiopeia" : "Cassiopeia",
    "TFT13_Chainsaw" : "Renni",
    "TFT13_Corki" : "Corki",
    "TFT13_Darius" : "Darius",
    "TFT13_Draven" : "Draven",
    "TFT13_DrMundo" : "Dr Mundo",
    "TFT13_Ekko" : "Ekko",
    "TFT13_Elise" : "Elise",
    "TFT13_Ezreal" : "Ezreal",
    "TFT13_Fish" : "Steb",
    "TFT13_FlyGuy" : "Scar",
    "TFT13_Gangplank" : "Gangplank",
    "TFT13_Garen" : "Garen",
    "TFT13_Gremlin" : "Smeech",
    "TFT13_Heimerdinger" : "Heimerdinger",
    "TFT13_Illaoi" : "Illaoi",
    "TFT13_Irelia" : "Irelia",
    "TFT13_Jayce" : "Jayce",
    "TFT13_JayceSummon" : "Jayce Summon",
    "TFT13_Jinx" : "Jinx",
    "TFT13_KogMaw" : "Kog Maw",
    "TFT13_LeBlanc" : "LeBlanc",
    "TFT13_Leona" : "Leona",
    "TFT13_Lieutenant" : "Sevika",
    "TFT13_Lux" : "Lux",
    "TFT13_Malzahar" : "Malzahar",
    "TFT13_MissMage" : "Mel",
    "TFT13_Mordekaiser" : "Mordekaiser",
    "TFT13_Morgana" : "Morgana",
    "TFT13_Nami" : "Nami",
    "TFT13_Nocturne" : "Nocturne",
    "TFT13_Prime" : "Vander",
    "TFT13_Red" : "Violet",
    "TFT13_Rell" : "Rell",
    "TFT13_RenataGlasc" : "Renata Glasc",
    "TFT13_Rumble" : "Rumble",
    "TFT13_Sett" : "Sett",
    "TFT13_Shooter" : "Maddie",
    "TFT13_Silco" : "Silco",
    "TFT13_Singed" : "Singed",
    "TFT13_Sion" : "Sion",
    "tft13_swain" : "Swain",
    "TFT13_Tristana" : "Tristana",
    "TFT13_Trundle" : "Trundle",
    "TFT13_TwistedFate" : "Twisted Fate",
    "TFT13_Twitch" : "Twitch",
    "TFT13_Urgot" : "Urgot",
    "TFT13_Vex" : "Vex",
    "TFT13_Vi" : "Vi",
    "TFT13_Viktor" : "Viktor",
    "TFT13_Vladimir" : "Vladimir",
    "TFT13_Warwick" : "Warwick",
    "TFT13_Zeri" : "Zeri",
    "TFT13_Ziggs" : "Ziggs",
    "TFT13_Zoe" : "Zoe",
    "TFT13_Zyra" : "Zyra"
}

Items_dict_tft13 = {
    "TFT_Item_WarmogsArmor" : "Warmog's Armor",
    "TFT_Item_GargoyleStoneplate" : "Gargoyle Stoneplate",
    "TFT_Item_RedBuff" : "Sunfire Cape",
    "TFT_Item_DragonsClaw" : "Dragon's Claw",
    "TFT_Item_IonicSpark" : "Ionic Spark"
}