Champions_dict_tft13 = {
    "TFT13_Akali" : "Akali",
    "TFT13_Ambessa" : "Ambessa",
    "TFT13_Amumu" : "Amumu",
    "TFT13_Beardy" : "Lloris",
    "TFT13_Blitzcrank" : "Blitzcrank",
    "TFT13_Blue" : "Powder",
    "TFT13_Caitlyn" : "Caitlyn",
    "TFT13_Camille" : "Camille",
    "TFT13_Cassiopeia" : "Cassiopeia",
    "TFT13_Chainsaw" : "Renni",
    "TFT13_Corki" : "Corki",
    "TFT13_Darius" : "Darius",
    "TFT13_Draven" : "Draven",
    "TFT13_DrMundo" : "Dr Mundo",
    "TFT13_Ekko" : "Ekko",
    "TFT13_Elise" : "Elise",
    "TFT13_Ezreal" : "Ezreal",
    "TFT13_Fish" : "Steb",
    "TFT13_FlyGuy" : "Scar",
    "TFT13_Gangplank" : "Gangplank",
    "TFT13_Garen" : "Garen",
    "TFT13_Gremlin" : "Smeech",
    "TFT13_Heimerdinger" : "Heimerdinger",
    "TFT13_Illaoi" : "Illaoi",
    "TFT13_Irelia" : "Irelia",
    "TFT13_Jayce" : "Jayce",
    "TFT13_JayceSummon" : "Jayce Summon",
    "TFT13_Jinx" : "Jinx",
    "TFT13_KogMaw" : "Kog Maw",
    "TFT13_LeBlanc" : "LeBlanc",
    "TFT13_Leona" : "Leona",
    "TFT13_Lieutenant" : "Sevika",
    "TFT13_Lux" : "Lux",
    "TFT13_Malzahar" : "Malzahar",
    "TFT13_MissMage" : "Mel",
    "TFT13_Mordekaiser" : "Mordekaiser",
    "TFT13_Morgana" : "Morgana",
    "TFT13_Nami" : "Nami",
    "TFT13_Nocturne" : "Nocturne",
    "TFT13_Prime" : "Vander",
    "TFT13_Red" : "Violet",
    "TFT13_Rell" : "Rell",
    "TFT13_RenataGlasc" : "Renata Glasc",
    "TFT13_Rumble" : "Rumble",
    "TFT13_Sett" : "Sett",
    "TFT13_Shooter" : "Maddie",
    "TFT13_Silco" : "Silco",
    "TFT13_Singed" : "Singed",
    "TFT13_Sion" : "Sion",
    "tft13_swain" : "Swain",
    "TFT13_Tristana" : "Tristana",
    "TFT13_Trundle" : "Trundle",
    "TFT13_TwistedFate" : "Twisted Fate",
    "TFT13_Twitch" : "Twitch",
    "TFT13_Urgot" : "Urgot",
    "TFT13_Vex" : "Vex",
    "TFT13_Vi" : "Vi",
    "TFT13_Viktor" : "Viktor",
    "TFT13_Vladimir" : "Vladimir",
    "TFT13_Warwick" : "Warwick",
    "TFT13_Zeri" : "Zeri",
    "TFT13_Ziggs" : "Ziggs",
    "TFT13_Zoe" : "Zoe",
    "TFT13_Zyra" : "Zyra"
}

Champions_dict_traits_tft13 = {
    "TFT13_Akali" : "Rebel, Quickstriker",
    "TFT13_Ambessa" : "Emissary, Quickstriker",
    "TFT13_Amumu" : "Watcher, Automata",
    "TFT13_Beardy" : "Enforcer, Sentinel",
    "TFT13_Blitzcrank" : "Automata, Dominator",
    "TFT13_Blue" : "Family, Scrap, Ambusher",
    "TFT13_Caitlyn" : "Enforcer, Sniper",
    "TFT13_Camille" : "Enforcer, Ambusher",
    "TFT13_Cassiopeia" : "Black Rose, Dominator",
    "TFT13_Chainsaw" : "Firelight, Watcher",
    "TFT13_Corki" : "Scrap, Artillerist",
    "TFT13_Darius" : "Conqueror, Watcher",
    "TFT13_Draven" : "Conqueror, Pit Fighter",
    "TFT13_DrMundo" : "Experiment, Dominator",
    "TFT13_Ekko" : "Scrap, Firelight, Ambusher",
    "TFT13_Elise" : "Black Rose, Bruiser, Form Swapper",
    "TFT13_Ezreal" : "Rebel, Artillerist, Academy",
    "TFT13_Fish" : "Bruiser, Enforcer",
    "TFT13_FlyGuy" : "Firelight, Watcher",
    "TFT13_Gangplank" : "Form Swapper, Scrap, Pit Fighter",
    "TFT13_Garen" : "Watcher, Emissary",
    "TFT13_Gremlin" : "Chem-Baron, Ambusher",
    "TFT13_Heimerdinger" : "Visionary, Academy",
    "TFT13_Illaoi" : "Sentinel, Rebel",
    "TFT13_Irelia" : "Sentinel, Rebel",
    "TFT13_Jayce" : "Form Swapper, Academy",
    "TFT13_JayceSummon" : "?????",
    "TFT13_Jinx" : "Ambusher, Rebel",
    "TFT13_KogMaw" : "Automata, Sniper",
    "TFT13_LeBlanc" : "Sorcerer, Black Rose",
    "TFT13_Leona" : "Sentinel, Academy",
    "TFT13_Lieutenant" : "Chem-Baron, Pit Fighter, Highroller",
    "TFT13_Lux" : "Sorcerer, Academy",
    "TFT13_Malzahar" : "Automata, Visionary",
    "TFT13_MissMage" : "Banished Mage",
    "TFT13_Mordekaiser" : "Conqueror, Dominator",
    "TFT13_Morgana" : "Black Rose, Visionary",
    "TFT13_Nami" : "Emissary, Sorcerer",
    "TFT13_Nocturne" : "Quicksriker, Automata",
    "TFT13_Prime" : "Family, Watcher",
    "TFT13_Red" : "Family, Pit Fighter",
    "TFT13_Rell" : "Visionary, Sentinel, Conqueror",
    "TFT13_RenataGlasc" : "Chem-Baron, Visionary",
    "TFT13_Rumble" : "Scrap, Sentinel, Junker King",
    "TFT13_Sett" : "Bruiser, Rebel",
    "TFT13_Shooter" : "Enforcer, Sniper",
    "TFT13_Silco" : "Chem-Baron, Dominator",
    "TFT13_Singed" : "Chem-Baron, Sentinel",
    "TFT13_Sion" : "??????",
    "tft13_swain" : "Form Swapper, Conqueror, Sorcerer",
    "TFT13_Tristana" : "Emissary, Artillerist",
    "TFT13_Trundle" : "Scrap, Bruiser",
    "TFT13_TwistedFate" : "Quickstriker, Enforcer",
    "TFT13_Twitch" : "Experiment, Sniper",
    "TFT13_Urgot" : "Experiment, Pit Fighter",
    "TFT13_Vex" : "Visionary, Rebel",
    "TFT13_Vi" : "Pit Fighter, Enforcer",
    "TFT13_Viktor" : "Machine Herald",
    "TFT13_Vladimir" : "Sorcerer, Watcher, Black Rose",
    "TFT13_Warwick" : "Experiment, Blood Hunter",
    "TFT13_Zeri" : "Firelight, Sniper",
    "TFT13_Ziggs" : "Dominator, Scrap",
    "TFT13_Zoe" : "Rebel, Sorcerer",
    "TFT13_Zyra" : "Experiment, Sorcerer"
}

Items_dict_tft13 = {
    # Items
    "TFT_Item_ArchangelsStaff": "Archangel's Staff",
    "TFT_Item_BFSword": "B.F. Sword",
    "TFT_Item_InfinityEdge" : "Infinity Edge",
    "TFT_Item_Bloodthirster": "Bloodthirster",
    "TFT_Item_BrambleVest": "Bramble Vest",
    "TFT_Item_BlueBuff" : "Blue buff",
    "TFT_Item_Chalice": "Chalice of Power",
    "TFT_Item_Deathblade": "Deathblade",
    "TFT_Item_DragonsClaw": "Dragon's Claw",
    "TFT_Item_GargoyleStoneplate": "Gargoyle Stoneplate",
    "TFT_Item_GiantsBelt": "Giant's Belt",
    "TFT_Item_GiantSlayer": "Giant Slayer",
    "TFT_Item_GuardianAngel" : "Edge Of Night",
    "TFT_Item_PowerGauntlet" : "Guardbreaker",
    "TFT_Item_MadredsBloodrazor" : "Giant Slayer",
    "TFT_Item_GuinsoosRageblade": "Guinsoo's Rageblade",
    "TFT_Item_HandOfJustice": "Hand of Justice",
    "TFT_Item_HextechGunblade": "Hextech Gunblade",
    "TFT_Item_IonicSpark": "Ionic Spark",
    "TFT_Item_JeweledGauntlet": "Jeweled Gauntlet",
    "TFT_Item_LastWhisper": "Last Whisper",
    "TFT_Item_Locket": "Locket of the Iron Solari",
    "TFT_Item_Morellonomicon": "Morellonomicon",
    "TFT_Item_UnstableConcoction" : "Hand Of Justice",
    "TFT_Item_NeedlesslyLargeRod": "Needlessly Large Rod",
    "TFT_Item_NegatronCloak": "Negatron Cloak",
    "TFT_Item_Quicksilver": "Quicksilver",
    "TFT_Item_Leviathan" : "Nashor's Tooth",
    "TFT_Item_RabadonsDeathcap": "Rabadon's Deathcap",
    "TFT_Item_RapidFireCannon": "Red buff",
    "TFT_Item_RedBuff": "Sunfire Cape",
    "TFT_Item_Redemption": "Redemption",
    "TFT_Item_RecurveBow": "Recurve Bow",
    "TFT_Item_RunaansHurricane": "Runaan's Hurricane",
    "TFT_Item_SeraphsEmbrace": "Blue Buff",
    "TFT_Item_SparringGloves": "Sparring Gloves",
    "TFT_Item_SpearOfShojin": "Spear of Shojin",
    "TFT_Item_StatikkShiv": "Statikk Shiv",
    "TFT_Item_TearOfTheGoddess": "Tear of the Goddess",
    "TFT_Item_ThiefsGloves": "Thief's Gloves",
    "TFT_Item_TitansResolve": "Titan's Resolve",
    "TFT_Item_WarmogsArmor": "Warmog's Armor",
    "TFT_Item_ZekesHerald": "Zeke's Herald",
    "TFT_Item_Zephyr": "Zephyr",
    "TFT_Item_ZzRotPortal": "Zz'Rot Portal",
    "TFT_Item_Spatula": "Spatula",
    "TFT_Item_SteraksGage": "Sterak's Gage",
    "TFT_Item_FrozenHeart": "Protector's Vow",
    "TFT_Item_TacticianCrown": "Tactician's Crown",
    "TFT_Item_TacticianShield": "Tactician's Shield",
    "TFT_Item_TacticianCape": "Tactician's Cape",
    "TFT_Item_SteadfastHeart": "Steadfast Heart",
    "TFT_Item_SpectralGauntlet": "Evenshroud",
    "TFT_Item_Crownguard": "Crownguard",
    "TFT_Item_NashorsTooth": "Nashor's Tooth",
    "TFT_Item_AdaptiveHelm": "Adaptive Helm",
    # Emblems
    "TFT13_Item_TacticianEmblem": "Tactician's Emblem",
    "TFT13_Item_ArtilleristEmblem": "Artillerist Emblem",
    "TFT13_Item_SorcererEmblem": "Sorcerer Emblem",
    "TFT13_Item_QuickstrikerEmblem": "Quickstriker Emblem",
    "TFT13_Item_BlackRoseEmblem": "Black Rose Emblem",
    "TFT13_Item_PitFighterEmblem": "Pit Fighter Emblem",
    "TFT13_Item_RebelEmblem": "Rebel Emblem",
    "TFT13_Item_VisionaryEmblem": "Visionary Emblem",
    "TFT13_Item_BruiserEmblem": "Bruiser Emblem",
    "TFT13_Item_ConquerorEmblem": "Conqueror Emblem",
    "TFT13_Item_AmbusherEmblem": "Ambusher Emblem",
    "TFT13_Item_AutomataEmblem": "Automata Emblem",
    "TFT13_Item_EnforcerEmblem": "Enforcer Emblem",
    "TFT13_Item_SentinelEmblem": "Sentinel Emblem",
    "TFT13_Item_ExperimentEmblem": "Experiment Emblem",
    "TFT13_Item_FamilyEmblemItem": "Family Emblem",
    "TFT13_Item_FirelightEmblem": "Firelight Emblem",
    "TFT13_Item_FryingPan": "Frying Pan",
    "TFT13_Item_TitanEmblemItem": "Sentinel Emblem",
    "TFT13_Item_ExperimentEmblem": "Experiment Emblem",
    "TFT13_Item_FamilyEmblem": "Family Emblem",
    "TFT13_Item_EnforcerEmblem": "Enforcer Emblem",
    "TFT13_Item_FirelightEmblem": "Firelight Emblem",
    "TFT13_Item_WarbandEmblemItem" : "Conqueror Emblem",
    "TFT13_Item_AmbusherEmblem": "Ambusher Emblem",
    "TFT13_Item_ArtilleristEmblem": "Artillerist Emblem",
    "TFT13_Item_SorcererEmblem": "Sorcerer Emblem",
    "TFT13_Item_QuickstrikerEmblem": "Quickstriker Emblem",
    "TFT13_Item_BlackRoseEmblem": "Black Rose Emblem",
    "TFT13_Item_PitFighterEmblemItem": "Pit Fighter Emblem",
    "TFT13_Item_RebelEmblem": "Rebel Emblem",
    "TFT13_Item_VisionaryEmblem": "Visionary Emblem",
    "TFT13_Item_BruiserEmblem": "Bruiser Emblem",
    "TFT13_Item_ConquerorEmblem": "Conqueror Emblem",
    "TFT13_Item_AutomataEmblem": "Automata Emblem",
    # Radiant Items
    "TFT5_Item_ArchangelsStaffRadiant": "Urf-Angel's Staff",
    "TFT5_Item_BFSwordRadiant": "Glamorous Gauntlet",
    "TFT5_Item_BloodthirsterRadiant": "Blessed Bloodthirster",
    "TFT5_Item_BrambleVestRadiant": "Rosethorn Vest",
    "TFT5_Item_ChaliceRadiant": "Chalice of Charity",
    "TFT5_Item_DeathbladeRadiant": "Luminous Deathblade",
    "TFT5_Item_DragonsClawRadiant": "Dragon's Will",
    "TFT5_Item_EdgeOfNightRadiant": "Brink of Dawn",
    "TFT5_Item_GargoyleStoneplateRadiant": "Dvarapala Stoneplate",
    "TFT5_Item_GiantsBeltRadiant": "Warmog's Pride",
    "TFT5_Item_GiantSlayerRadiant": "Demonslayer",
    "TFT5_Item_GuinsoosRagebladeRadiant": "Guinsoo's Reckoning",
    "TFT5_Item_HandOfJusticeRadiant": "Fist of Fairness",
    "TFT5_Item_HextechGunbladeRadiant": "Hextech Lifeblade",
    "TFT5_Item_IonicSparkRadiant": "Covalent Spark",
    "TFT5_Item_JeweledGauntletRadiant": "Radiant Jeweled Gauntlet",
    "TFT5_Item_LastWhisperRadiant": "Eternal Whisper",
    "TFT5_Item_LocketRadiant": "Locket of Targon Prime",
    "TFT5_Item_MorellonomiconRadiant": "More Morellonomicon",
    "TFT5_Item_QuicksilverRadiant": "Vengeful Quicksilver",
    "TFT5_Item_RabadonsDeathcapRadiant": "Rabadon's Ascended Cap",
    "TFT5_Item_RapidFireCannonRadiant": "Rapid Lightcannon",
    "TFT5_Item_SeraphsEmbraceRadiant": "Seraph's Sanctum",
    "TFT5_Item_SpearOfShojinRadiant": "Spear of Hirana",
    "TFT5_Item_StatikkShivRadiant": "Statikk's Favor",
    "TFT5_Item_TitansResolveRadiant": "Titan's Vow",
     # Ornn (Artifact) Items
    "TFT7_Item_ShimmerscaleGamblersBlade" : "Gambler's Blade",
    "TFT4_Item_AnimaVisage": "Anima Visage",
    "TFT4_Item_DeathsDefiance": "Death's Defiance",
    "TFT4_Item_ObsidianCleaver": "Obsidian Cleaver",
    "TFT4_Item_ForgefireCape": "Forgefire Crest",
    "TFT4_Item_InfinityForce": "Infinity Force",
    "TFT4_Item_Muramana": "Muramana",
    "TFT4_Item_RanduinsSanctum": "Randuin's Sanctum",
    "TFT4_Item_TheCollector": "Collector",
    "TFT4_Item_ZzRotPortal": "Zz'Rot's Invitation",
    "TFT4_Item_Manazane": "Manazane",
    "TFT4_Item_SunlightCape": "Sunlight Cape",
    "TFT4_Item_WarmogsPride": "Warmog's Pride",
    "TFT4_Item_Equinox": "Equinox",
    "TFT4_Item_Absolution": "Absolution",
    "TFT4_Item_BulwarksOath": "Bulwark's Oath",
    "TFT4_Item_Covenant": "Covenant",
    "TFT4_Item_DragonsWill": "Dragon's Will",
    "TFT4_Item_FistOfFairness": "Fist of Fairness",
    "TFT4_Item_GlamorousGauntlet": "Glamorous Gauntlet",
    "TFT4_Item_GuardianAngel": "Guardian Angel",
    "TFT4_Item_HandOfJustice": "Hand of Justice",
    "TFT4_Item_HextechGunblade": "Hextech Gunblade",
    "TFT4_Item_IonicSpark": "Ionic Spark",
    "TFT4_Item_JeweledGauntlet": "Jeweled Gauntlet",
    "TFT4_Item_LastWhisper": "Last Whisper",
    "TFT4_Item_LocketOfTheIronSolari": "Locket of the Iron Solari",
    "TFT4_Item_Morellonomicon": "Morellonomicon",
    "TFT4_Item_Quicksilver": "Quicksilver",
    "TFT4_Item_RabadonsDeathcap": "Rabadon's Deathcap",
    "TFT4_Item_RapidFirecannon": "Rapid Firecannon",
    "TFT4_Item_SeraphsEmbrace": "Seraph's Embrace",
    "TFT4_Item_SpearOfShojin": "Spear of Shojin",
    "TFT4_Item_StatikkShiv": "Statikk Shiv",
    "TFT4_Item_TitansResolve": "Titan's Resolve",
    "TFT4_Item_ZekesHerald": "Zeke's Herald",
    "TFT4_Item_Zephyr": "Zephyr",
    "TFT4_Item_ZzRotPortal": "Zz'Rot Portal"
}